language: go

go:
  - tip

sudo: false

before_install:
  - echo -e "machine api.github.com login douglarek password $GITHUB_TOKEN" >> ~/.netrc

install:
  - go get -u -x golang.org/x/vgo
  - vgo build -v -x

script:
  - vgo test ./...
