language: go

go:
  - "1.12rc1"

sudo: false

before_install:
  - echo -e "machine api.github.com login douglarek password $GITHUB_TOKEN" >> ~/.netrc

env:
  - GO111MODULE=on GOPROXY=https://athens.azurefd.net/

install:
  - go build -v -x

script:
  - go test ./...
